name: CI com Testes Automatizados

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
    
    - name: Configurar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Instalar dependências
      run: npm install
    
    - name: Executar testes
      run: npm test
    
    - name: Gerar relatório de cobertura
      run: npm run test:coverage
    
    - name: Upload relatório de cobertura
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/
