name: CI com ESLint

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Listar arquivos na raiz
        run: ls -la

      - name: Remover node_modules (se existir)
        run: rm -rf node_modules || true

      - name: Instalar dependências
        run: npm install

      - name: Dar permissão no eslint
        run: chmod +x ./node_modules/.bin/eslint

      - name: Rodar ESLint
        run: ./node_modules/.bin/eslint .


